"""Constantes del sistema de batalla"""

# Damage calculation
CRIT_MULTIPLIER = 2
STAB_MULTIPLIER = 1.5
MIN_RANDOM_FACTOR = 217
MAX_RANDOM_FACTOR = 255
RANDOM_DIVISOR = 255

# Status effects
FREEZE_THAW_CHANCE = 0.2
PARALYSIS_FAIL_CHANCE = 0.25
BURN_DAMAGE_FRACTION = 16
POISON_DAMAGE_FRACTION = 16
BURN_ATTACK_MULTIPLIER = 0.5

# Sleep
MIN_SLEEP_TURNS = 1
MAX_SLEEP_TURNS = 7
