"""Battle Events Module - Event-driven architecture for battle messaging"""

from .types import (
    EventType,
    BattleEvent,
    # Battle flow
    BattleStartEvent,
    BattleEndEvent,
    TurnStartEvent,
    TurnEndEvent,
    # Combat
    MoveUsedEvent,
    DamageDealtEvent,
    CriticalHitEvent,
    EffectivenessEvent,
    MoveMissedEvent,
    MoveFailedEvent,
    MoveNoEffectEvent,
    # Multi-hit
    MultiHitStrikeEvent,
    MultiHitCompleteEvent,
    # Status
    StatusAppliedEvent,
    StatusCuredEvent,
    StatusDamageEvent,
    StatusPreventedActionEvent,
    ConfusionSelfHitEvent,
    # Stats
    StatChangedEvent,
    StatLimitReachedEvent,
    # Screens
    ScreenActivatedEvent,
    ScreenExpiredEvent,
    ScreenBlockedEvent,
    ScreenReducedDamageEvent,
    # HP changes
    PokemonHealedEvent,
    PokemonFaintedEvent,
    HPDrainedEvent,
    # Special mechanics
    PokemonTrappedEvent,
    TrapDamageEvent,
    TrapEscapedEvent,
    SubstituteCreatedEvent,
    SubstituteBrokeEvent,
    SubstituteBlockedEvent,
    RechargeNeededEvent,
    ChargingMoveEvent,
    RageIncreasedEvent,
    LeechSeedPlantedEvent,
    LeechSeedDamageEvent,
    MistProtectionEvent,
    MoveDisabledEvent,
    MoveReenabledEvent,
    InfoEvent,
)

from .bus import (
    BattleEventBus,
    EventHandler,
    get_event_bus,
    set_event_bus,
    reset_event_bus,
)

__all__ = [
    # Types
    'EventType',
    'BattleEvent',
    'BattleStartEvent',
    'BattleEndEvent',
    'TurnStartEvent',
    'TurnEndEvent',
    'MoveUsedEvent',
    'DamageDealtEvent',
    'CriticalHitEvent',
    'EffectivenessEvent',
    'MoveMissedEvent',
    'MoveFailedEvent',
    'MoveNoEffectEvent',
    'MultiHitStrikeEvent',
    'MultiHitCompleteEvent',
    'StatusAppliedEvent',
    'StatusCuredEvent',
    'StatusDamageEvent',
    'StatusPreventedActionEvent',
    'ConfusionSelfHitEvent',
    'StatChangedEvent',
    'StatLimitReachedEvent',
    'ScreenActivatedEvent',
    'ScreenExpiredEvent',
    'ScreenBlockedEvent',
    'ScreenReducedDamageEvent',
    'PokemonHealedEvent',
    'PokemonFaintedEvent',
    'HPDrainedEvent',
    'PokemonTrappedEvent',
    'TrapDamageEvent',
    'TrapEscapedEvent',
    'SubstituteCreatedEvent',
    'SubstituteBrokeEvent',
    'SubstituteBlockedEvent',
    'RechargeNeededEvent',
    'ChargingMoveEvent',
    'RageIncreasedEvent',
    'LeechSeedPlantedEvent',
    'LeechSeedDamageEvent',
    'MistProtectionEvent',
    'MoveDisabledEvent',
    'MoveReenabledEvent',
    'InfoEvent',
    # Bus
    'BattleEventBus',
    'EventHandler',
    'get_event_bus',
    'set_event_bus',
    'reset_event_bus',
]
